HW-262: Styling mailing schedule page
compucorp/uk.co.vedaconsulting.mosaico pull request #4
Opened 2017-03-29 13:55 UTC by meladawy

Changes in styling to match the target design for "New Mailing > Options" page

Before:
![screen shot 2017-03-29 at 3 45 55 pm](https://cloud.githubusercontent.com/assets/2423218/24458000/feda6d56-1497-11e7-932d-24666a91eec5.png)

After:
![screen shot 2017-03-29 at 3 46 58 pm](https://cloud.githubusercontent.com/assets/2423218/24458004/021c806c-1498-11e7-8a9c-413aabc9380b.png)

2017-03-30 12:26 UTC, boriszaydlin commented on sass/mosaico/_form.scss
> +  select {
please include name values into quotes `&[name="optout_id"]`
same below and above

2017-03-30 12:39 UTC, boriszaydlin commented on css/legacy.css
> +#bootstrap-theme .crm-mosaico-page .helpicon{background-color:#42afcb}
This is not same as here https://github.com/compucorp/uk.co.vedaconsulting.mosaico/pull/4/files#diff-1e6bdecc7a4b9016c394ff3e70c9209dL2
You added space between this two selectors `#bootstrap-theme .crm-mosaico-page`, check if we really need this

2017-03-30 12:43 UTC, boriszaydlin commented on sass/civicrm-override/4.6.scss
> +// This file should be called only if the current version is 4.6
It is import file, don't we need to add `_` for filename: `_4.6.scss` ?

2017-03-30 12:45 UTC, boriszaydlin commented on sass/mosaico/_form.scss
> +
Please use quotes `[name="campaign"]`, same below

2017-03-30 12:47 UTC, boriszaydlin commented on gulpfile.js
> +gulp.task('watch', function () {
use two spaces tab indent

2017-03-30 13:07 UTC, AkA84 requested changes

2017-03-30 13:07 UTC, AkA84 commented on gulpfile.js
> +  .pipe(gulp.dest('./css/'))
the two tasks "bodies" are basically the same, only the `src()` argument is different. So you should unify them in, say, the same function

2017-03-30 13:07 UTC, AkA84 commented on sass/_variables.scss
> +$brand-primary:                           #42AFCB;
this is a bootstrap variable, why is it needed here?

2017-03-30 15:58 UTC, meladawy commented on sass/mosaico/_form.scss
> +
Fixed in a new commit 
https://github.com/compucorp/uk.co.vedaconsulting.mosaico/pull/4/commits/5635e5d993ba9e502acf3d9a9c0d0c75d3b32dca

2017-03-30 15:59 UTC, meladawy commented on sass/_variables.scss
> +$brand-primary:                           #42AFCB;
Its required by this file 
https://github.com/compucorp/uk.co.vedaconsulting.mosaico/pull/4/files#diff-a9e67b892cd069c8d017d3e8687d28f4

I get "Variable not defined" error if i removed it from _variables.scss

2017-03-31 11:39 UTC, meladawy commented
@AkA84 I installed CivicrmSassRoot and replaced local variables with shoreditsh variables 

https://github.com/compucorp/uk.co.vedaconsulting.mosaico/pull/4/commits/6076ccb8359fb1f60abe278326b6190d5e790316

2017-03-31 11:46 UTC, AkA84 approved these changes

2017-03-31 11:48 UTC, boriszaydlin approved these changes

2017-03-31 11:49 UTC, merged